//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Miscellaneous {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Miscellaneous() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Resources.Miscellaneous", typeof(Miscellaneous).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a player to fire....
        /// </summary>
        internal static string ActionDirectorTargetSelect {
            get {
                return ResourceManager.GetString("ActionDirectorTargetSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish This Day.
        /// </summary>
        internal static string ActionFinishEveningButton {
            get {
                return ResourceManager.GetString("ActionFinishEveningButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Badge and Confirm Attendance.
        /// </summary>
        internal static string ActionIntroReadyButton {
            get {
                return ResourceManager.GetString("ActionIntroReadyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start The Board Meeting.
        /// </summary>
        internal static string ActionMorningStartBoardButton {
            get {
                return ResourceManager.GetString("ActionMorningStartBoardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💻 Open Terminal.
        /// </summary>
        internal static string ActionOpenTerminalButton {
            get {
                return ResourceManager.GetString("ActionOpenTerminalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an active game session for this guild. Please wait until it ends..
        /// </summary>
        internal static string ActiveGameSessionExistsError {
            get {
                return ResourceManager.GetString("ActiveGameSessionExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Position to Pool (Host Only).
        /// </summary>
        internal static string AddRoleToListTitle {
            get {
                return ResourceManager.GetString("AddRoleToListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Attendance confirmed..
        /// </summary>
        internal static string AttendanceConfirmMessage {
            get {
                return ResourceManager.GetString("AttendanceConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Attention!.
        /// </summary>
        internal static string AttentionTitle {
            get {
                return ResourceManager.GetString("AttentionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☀️ **Board meeting is starting:** Please proceed to the meeting room..
        /// </summary>
        internal static string BoardMeetingStartTitle {
            get {
                return ResourceManager.GetString("BoardMeetingStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have candidates for firing!.
        /// </summary>
        internal static string CandidateForFireExistInfo {
            get {
                return ResourceManager.GetString("CandidateForFireExistInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate registered in the system. Click -Fire- to confirm..
        /// </summary>
        internal static string CandidateRegisteredToFireInfo {
            get {
                return ResourceManager.GetString("CandidateRegisteredToFireInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Candidates:**.
        /// </summary>
        internal static string CandidatesTitle {
            get {
                return ResourceManager.GetString("CandidatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ This option is only available after using the Veto Right or if there is no candidates for firing..
        /// </summary>
        internal static string CannotSkipBoardError {
            get {
                return ResourceManager.GetString("CannotSkipBoardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your private messages to sign the employment contract..
        /// </summary>
        internal static string CheckPMForContractInfo {
            get {
                return ResourceManager.GetString("CheckPMForContractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Role Pool.
        /// </summary>
        internal static string ClearRolesButton {
            get {
                return ResourceManager.GetString("ClearRolesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string ClearTargetSelectionButton {
            get {
                return ResourceManager.GetString("ClearTargetSelectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚖️ Decision Made.
        /// </summary>
        internal static string DecisionMadeTitle {
            get {
                return ResourceManager.GetString("DecisionMadeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Board is over.** The fired employee has time to say their final words..
        /// </summary>
        internal static string DirectorBoardOverTitle {
            get {
                return ResourceManager.GetString("DirectorBoardOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director Board.
        /// </summary>
        internal static string DirectorBoardTitle {
            get {
                return ResourceManager.GetString("DirectorBoardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The General Director has decided to show mercy. No one will be terminated today..
        /// </summary>
        internal static string DirectorDecisionMercyInfo {
            get {
                return ResourceManager.GetString("DirectorDecisionMercyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ You have interrupted the debates and concluded the workday..
        /// </summary>
        internal static string DirectorInterruptDebateInfo {
            get {
                return ResourceManager.GetString("DirectorInterruptDebateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The General Director has made their decision. Employee &lt;@{0}&gt; has been terminated from the corporation..
        /// </summary>
        internal static string DirectorMadeDesicionInfo {
            get {
                return ResourceManager.GetString("DirectorMadeDesicionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory of job positions.
        /// </summary>
        internal static string DirectoryRolesTitle {
            get {
                return ResourceManager.GetString("DirectoryRolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Fire Anyone.
        /// </summary>
        internal static string DontFireButton {
            get {
                return ResourceManager.GetString("DontFireButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this document to anyone!.
        /// </summary>
        internal static string DontShowDocumentWarning {
            get {
                return ResourceManager.GetString("DontShowDocumentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤝 DRAW!.
        /// </summary>
        internal static string DrawTitle {
            get {
                return ResourceManager.GetString("DrawTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The market collapsed. No winner was identified, and the corporation was declared bankrupt..
        /// </summary>
        internal static string DrawWinnerTitle {
            get {
                return ResourceManager.GetString("DrawWinnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee &lt;@{0}&gt; must reveal their identity..
        /// </summary>
        internal static string EmployeeMustRevealRoleInfo {
            get {
                return ResourceManager.GetString("EmployeeMustRevealRoleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 **The game session has been deleted from the system&apos;s memory.** Any interaction with terminals and buttons is blocked. You can discuss the game results here. The organizer can manually delete this channel..
        /// </summary>
        internal static string EndGameSessionDeleteTitle {
            get {
                return ResourceManager.GetString("EndGameSessionDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Office.
        /// </summary>
        internal static string EnterLobbyButton {
            get {
                return ResourceManager.GetString("EnterLobbyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Failed to Start the Game.
        /// </summary>
        internal static string FailedStartGameError {
            get {
                return ResourceManager.GetString("FailedStartGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        internal static string FailTitle {
            get {
                return ResourceManager.GetString("FailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Your final words have been recorded. The workday is complete..
        /// </summary>
        internal static string FinalWordRecorderTitle {
            get {
                return ResourceManager.GetString("FinalWordRecorderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Fired:**.
        /// </summary>
        internal static string FiredTitle {
            get {
                return ResourceManager.GetString("FiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Player.
        /// </summary>
        internal static string FirePlayerButton {
            get {
                return ResourceManager.GetString("FirePlayerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏆 GAME OVER!.
        /// </summary>
        internal static string GameOverTitle {
            get {
                return ResourceManager.GetString("GameOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone is safe... for now. The General Director now can choose anyone to fire on their will... or do not choose at all..
        /// </summary>
        internal static string GeneralDirectorCanSelectCandidateReminder {
            get {
                return ResourceManager.GetString("GeneralDirectorCanSelectCandidateReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host has left the lobby. The meeting is cancelled..
        /// </summary>
        internal static string HostLeftLobbyInfo {
            get {
                return ResourceManager.GetString("HostLeftLobbyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 **Welcome to Paranoia Corp!** The introductory day is starting. Introductory Day is about to begin. Please collect your job badge and confirm your attendance..
        /// </summary>
        internal static string IntroDayMessageInfo {
            get {
                return ResourceManager.GetString("IntroDayMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Launch Error:**.
        /// </summary>
        internal static string LaunchError {
            get {
                return ResourceManager.GetString("LaunchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the Office.
        /// </summary>
        internal static string LeaveLobbyButton {
            get {
                return ResourceManager.GetString("LeaveLobbyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚫 Lobby disbanded.
        /// </summary>
        internal static string LobbyDispandedInfo {
            get {
                return ResourceManager.GetString("LobbyDispandedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☕ Morning Coffee (Lobby).
        /// </summary>
        internal static string MorningCoffeeLobbyTitle {
            get {
                return ResourceManager.GetString("MorningCoffeeLobbyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☕ **Morning Briefing:** Review the nightly events and prepare for the board meeting..
        /// </summary>
        internal static string MorningReadyMessageInfo {
            get {
                return ResourceManager.GetString("MorningReadyMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the terminal..
        /// </summary>
        internal static string NoAccessTerminalError {
            get {
                return ResourceManager.GetString("NoAccessTerminalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No candidates for firing this round!.
        /// </summary>
        internal static string NoCandidatesForFireInfo {
            get {
                return ResourceManager.GetString("NoCandidatesForFireInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ First, choose an employee from the list..
        /// </summary>
        internal static string NoPlayerChosenToFireError {
            get {
                return ResourceManager.GetString("NoPlayerChosenToFireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players in the office..
        /// </summary>
        internal static string NoPlayersInLobbyInfo {
            get {
                return ResourceManager.GetString("NoPlayersInLobbyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observe: The number of players must match the number of roles in the pool..
        /// </summary>
        internal static string ObservePlayerNumberEqualsRolesWarning {
            get {
                return ResourceManager.GetString("ObservePlayerNumberEqualsRolesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Only the General Director can make personnel decisions..
        /// </summary>
        internal static string OnlyDirectorMakeDecision {
            get {
                return ResourceManager.GetString("OnlyDirectorMakeDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ **Access Denied:** Only the General Director or the fired employee can end the day..
        /// </summary>
        internal static string OnlyDirectorOrFiredPlayerEndDayError {
            get {
                return ResourceManager.GetString("OnlyDirectorOrFiredPlayerEndDayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ **Access Denied:** Only the General Director has the right to open the Board meeting..
        /// </summary>
        internal static string OnlyDirectorStartBoardError {
            get {
                return ResourceManager.GetString("OnlyDirectorStartBoardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the host can configure the role pool.
        /// </summary>
        internal static string OnlyHostCanConfigureRoleError {
            get {
                return ResourceManager.GetString("OnlyHostCanConfigureRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the host can start the game..
        /// </summary>
        internal static string OnlyHostCanStartGameError {
            get {
                return ResourceManager.GetString("OnlyHostCanStartGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HR department was unable to deliver contracts to the following individuals: {0}. **Please allow the server to send you Direct Messages in your privacy settings!**.
        /// </summary>
        internal static string OpenDMWarning {
            get {
                return ResourceManager.GetString("OpenDMWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Silent night. No activity recorded.*.
        /// </summary>
        internal static string OvertimeNoActionHappenedInfo {
            get {
                return ResourceManager.GetString("OvertimeNoActionHappenedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ You have finished working in the terminal. The system has recorded your input. Wait for your colleagues..
        /// </summary>
        internal static string OvertimeReadyMessage {
            get {
                return ResourceManager.GetString("OvertimeReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        internal static string OvertimeTitle {
            get {
                return ResourceManager.GetString("OvertimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏢 Paranoia Corp - Session.
        /// </summary>
        internal static string ParanoiaCorpSessionTitle {
            get {
                return ResourceManager.GetString("ParanoiaCorpSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in the lobby..
        /// </summary>
        internal static string PlayerAlreadyInLobbyError {
            get {
                return ResourceManager.GetString("PlayerAlreadyInLobbyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in the lobby..
        /// </summary>
        internal static string PlayerIsNotInLobbyError {
            get {
                return ResourceManager.GetString("PlayerIsNotInLobbyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players in the office: {0}..
        /// </summary>
        internal static string PlayersInLobbyInfo {
            get {
                return ResourceManager.GetString("PlayersInLobbyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Position:**.
        /// </summary>
        internal static string PositionTitle {
            get {
                return ResourceManager.GetString("PositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📬 **You got a post message:**.
        /// </summary>
        internal static string PostMessageInfo {
            get {
                return ResourceManager.GetString("PostMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while preparing the game session.
        /// </summary>
        internal static string PrepareGameUnexpectedError {
            get {
                return ResourceManager.GetString("PrepareGameUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyButton {
            get {
                return ResourceManager.GetString("ReadyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Responsibilities:**.
        /// </summary>
        internal static string ResponsobilityTitle {
            get {
                return ResourceManager.GetString("ResponsobilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Pool.
        /// </summary>
        internal static string RoleListTitle {
            get {
                return ResourceManager.GetString("RoleListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions in the pool.
        /// </summary>
        internal static string RolesInListTitle {
            get {
                return ResourceManager.GetString("RolesInListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the first target to exercise your authority....
        /// </summary>
        internal static string SelectFirstTargetMessage {
            get {
                return ResourceManager.GetString("SelectFirstTargetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the second target to exercise your authority....
        /// </summary>
        internal static string SelectSecondTargetMessage {
            get {
                return ResourceManager.GetString("SelectSecondTargetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a target to exercise your authority, or simply skip turn..
        /// </summary>
        internal static string SelectTargetMessage {
            get {
                return ResourceManager.GetString("SelectTargetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 START THE WORKDAY.
        /// </summary>
        internal static string StartGameButton {
            get {
                return ResourceManager.GetString("StartGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected target not found..
        /// </summary>
        internal static string TargetNotFoundError {
            get {
                return ResourceManager.GetString("TargetNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All target selections have been cleared. Click -Ready- if you want to skip your turn..
        /// </summary>
        internal static string TargetSelectionClearedMessage {
            get {
                return ResourceManager.GetString("TargetSelectionClearedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ **Warning:** You haven&apos;t finished your selection! Please select ALL required targets, or clear selection and then skip your turn..
        /// </summary>
        internal static string TargetSelectionNotFinishedError {
            get {
                return ResourceManager.GetString("TargetSelectionNotFinishedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please close and reopen the terminal..
        /// </summary>
        internal static string TerminalSessionExpiredWarning {
            get {
                return ResourceManager.GetString("TerminalSessionExpiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💻 Corporate Terminal (Overtime).
        /// </summary>
        internal static string TerminalTitle {
            get {
                return ResourceManager.GetString("TerminalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Their Position:**.
        /// </summary>
        internal static string TheirPositionTitle {
            get {
                return ResourceManager.GetString("TheirPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📢 **Token Notification** You have {0} reports left to write..
        /// </summary>
        internal static string TokenNotificationInfo {
            get {
                return ResourceManager.GetString("TokenNotificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Day {0}.
        /// </summary>
        internal static string TurnNumberTitle {
            get {
                return ResourceManager.GetString("TurnNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Unexpected Error**.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can be only one unique role..
        /// </summary>
        internal static string UniqueRolePresentError {
            get {
                return ResourceManager.GetString("UniqueRolePresentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Veto.
        /// </summary>
        internal static string UseVetoButton {
            get {
                return ResourceManager.GetString("UseVetoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Only the General Director can use the Veto power..
        /// </summary>
        internal static string UseVetoDeniedError {
            get {
                return ResourceManager.GetString("UseVetoDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The General Director has {0} vetoes remaining..
        /// </summary>
        internal static string VetoReminderMessage {
            get {
                return ResourceManager.GetString("VetoReminderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **General Director** used the Veto power.\n The list of candidates for dismissal has been expanded to all living employees. The Director can also decide not to dismiss anyone..
        /// </summary>
        internal static string VetoUsedInfo {
            get {
                return ResourceManager.GetString("VetoUsedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Board Meeting (Veto Used!).
        /// </summary>
        internal static string VetoUsedWarning {
            get {
                return ResourceManager.GetString("VetoUsedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Roles.
        /// </summary>
        internal static string ViewRolesButton {
            get {
                return ResourceManager.GetString("ViewRolesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for employees to start the workday..
        /// </summary>
        internal static string WaitingForEmployeesInfo {
            get {
                return ResourceManager.GetString("WaitingForEmployeesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Corporate War is over. The winning faction is: **{0}**.
        /// </summary>
        internal static string WinnerFactionTitle {
            get {
                return ResourceManager.GetString("WinnerFactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌙 **Workday is over.** Overtime begins. The office is closed. Open the terminal to perform action you want to and click -Ready-..
        /// </summary>
        internal static string WorkdayOverTitle {
            get {
                return ResourceManager.GetString("WorkdayOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏢 Working Day Has Started!.
        /// </summary>
        internal static string WorkingDayStartTitle {
            get {
                return ResourceManager.GetString("WorkingDayStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose yourself or the same target!.
        /// </summary>
        internal static string YouCanSelectYourselfInfo {
            get {
                return ResourceManager.GetString("YouCanSelectYourselfInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ You have no more Veto power or it has already been used in this cycle..
        /// </summary>
        internal static string YouNotHaveVetoError {
            get {
                return ResourceManager.GetString("YouNotHaveVetoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not registered for this game..
        /// </summary>
        internal static string YouNotInGameError {
            get {
                return ResourceManager.GetString("YouNotInGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ You have successfully opened the board. Employees are invited to the meeting..
        /// </summary>
        internal static string YouOpenBoardMessage {
            get {
                return ResourceManager.GetString("YouOpenBoardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 Your Employment Contract.
        /// </summary>
        internal static string YourContractInfo {
            get {
                return ResourceManager.GetString("YourContractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Your Position:**.
        /// </summary>
        internal static string YourPositionTitle {
            get {
                return ResourceManager.GetString("YourPositionTitle", resourceCulture);
            }
        }
    }
}
