//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoleDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Resources.RoleDescriptions", typeof(RoleDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can communicate overtime in the &quot;Former Colleagues Club&quot; chat (with dismissed players).
        ///You can communicate overtime in the Outsource faction chat.
        ///You cannot be lured to the Startup.
        ///Unique position..
        /// </summary>
        internal static string AlumniManager {
            get {
                return ResourceManager.GetString("AlumniManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You submit a &quot;Critical Incompetence Memo&quot; to the Director on any target (works like a Compromising Material).
        ///You have a limited number of memos per game. Formula: number of players / 4. Minimum 2..
        /// </summary>
        internal static string AnticrisisManager {
            get {
                return ResourceManager.GetString("AnticrisisManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you investigate the activity of one employee. The next shift, you find out their exact position.
        ///If the target is a Shadow Director, the system generates any existing loyal position..
        /// </summary>
        internal static string Auditor {
            get {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extra-curricular duties (just sleep at home)..
        /// </summary>
        internal static string Clerk {
            get {
                return ResourceManager.GetString("Clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you can communicate with other Startup Evangelists.
        ///You do not know who the Startup Founder is and cannot communicate with them directly..
        /// </summary>
        internal static string Evangelist {
            get {
                return ResourceManager.GetString("Evangelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mandatory, unique, open role.
        ///You cannot be targeted. No overtime authority. During the day, you make sole decisions on dismissals.
        ///You have two &quot;Veto Powers&quot; per game..
        /// </summary>
        internal static string GeneralDirector {
            get {
                return ResourceManager.GetString("GeneralDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you can lock the account of one target. A locked target cancels all their actions during that overtime. You cannot hack the same employee on two consecutive shifts.
        ///Can communicate with the Syndicate during overtime..
        /// </summary>
        internal static string Hacker {
            get {
                return ResourceManager.GetString("Hacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During each overtime, you hide the personnel file of one employee (protection). If compromising information was collected on this target during this overtime, it will not be submitted to the Director in the morning.
        ///If there were more than one attempt to fire the target during this shift, the HR manager will be unable to save them from dismissal, regardless of the number of HR managers who tried to save the employee..
        /// </summary>
        internal static string HRManager {
            get {
                return ResourceManager.GetString("HRManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overtime authority.
        ///You can be recruited by the Shadow Director to become a Spy..
        /// </summary>
        internal static string Intern {
            get {
                return ResourceManager.GetString("Intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overtime authority.
        ///If incriminating evidence is fabricated against you during overtime, the file is mysteriously lost and doesn&apos;t appear on the Director&apos;s desk in the morning. Instead, you secretly switch to the Outsource faction and assume the Outsourcer role.
        ///If incriminating evidence is collected on you two or more times during a single overtime period, you manage to switch roles, but the incriminating evidence still ends up on the Director&apos;s desk..
        /// </summary>
        internal static string LayoffCandidate {
            get {
                return ResourceManager.GetString("LayoffCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select one target to fabricate incriminating evidence. In the morning, this target will be placed on the Director&apos;s mandatory dismissal list.
        ///If there are multiple Masters in the game, the target is randomly selected from among those suggested by them.
        ///You can communicate with all Syndicate members in encrypted chat during overtime..
        /// </summary>
        internal static string MasterOfCompromising {
            get {
                return ResourceManager.GetString("MasterOfCompromising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you offer a contract to a dismissed employee, regardless of how many attempts to dismiss the employee were made during the shift.
        ///If the selected target is dismissed during the same shift, they become an Outsourcer.
        ///If there are multiple Outsourcers, they only select one target for all. Cannot hire dismissed employees from the Outsource faction.
        ///You can chat with the Outsource faction during overtime..
        /// </summary>
        internal static string Outsourcer {
            get {
                return ResourceManager.GetString("Outsourcer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you can select two employees and force the first to use their job ability on the second (even if the first intended to skip a turn).
        ///The first target and the second target can be the same (the employee uses the skill on themselves).
        ///You can select yourself as the second target.
        ///If there are multiple Masters of Compromising and the Political Consultant forces one of them to fire someone, more than one person can be fired during this shift (this Master acts outside of the Syndicate&apos;s random t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PoliticalStrategist {
            get {
                return ResourceManager.GetString("PoliticalStrategist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, either block or dismiss the target. The result is determined randomly..
        /// </summary>
        internal static string Raider {
            get {
                return ResourceManager.GetString("Raider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the overtime, you swap the tasks of two employees. As a result, all overtime activities directed at them are redirected toward each other..
        /// </summary>
        internal static string ScrumMaster {
            get {
                return ResourceManager.GetString("ScrumMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You check one employee against the database during overtime. During the same shift, their loyalty (faction) is also determined.
        ///If the target is a Shadow Director or Startup Founder, the system displays them as loyal to the Corporation..
        /// </summary>
        internal static string SecuritySpecialist {
            get {
                return ResourceManager.GetString("SecuritySpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you can select a target for recruitment into the Syndicate. The transition occurs by morning.
        ///If the target is an Intern, he becomes a Spy.
        ///If the target is a System Administrator, he becomes a Hacker.
        ///Other targets remain in their positions but receive an email notification about a tempting contract (recruitment attempt).
        ///He has a golden parachute: attempting to fabricate incriminating evidence during overtime will end in failure.
        ///Cannot be recruited into the Startup.
        ///Can communicate with  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShadowDirector {
            get {
                return ResourceManager.GetString("ShadowDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overtime authority.
        ///You have an access to a private chat with other Corporation Shareholders..
        /// </summary>
        internal static string Shareholder {
            get {
                return ResourceManager.GetString("Shareholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you infiltrate databases and studies the activities of a single employee. At the end of overtime, you learn the exact role of the targeted player.
        ///You can communicate with all Syndicate members via encrypted chat during overtime..
        /// </summary>
        internal static string Spy {
            get {
                return ResourceManager.GetString("Spy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you entice one employee with stock options, luring him to the Startup.
        ///You see the work chat of all his Evangelists, but doesn&apos;t post there yourself. You know all the people you&apos;ve lured.
        ///A unique position..
        /// </summary>
        internal static string StartupFounder {
            get {
                return ResourceManager.GetString("StartupFounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During overtime, you can block access to a single target&apos;s servers. The target cancels all their actions.
        ///You can be recruited by the Shadow Director and become a Hacker..
        /// </summary>
        internal static string SystemAdministrator {
            get {
                return ResourceManager.GetString("SystemAdministrator", resourceCulture);
            }
        }
    }
}
