//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoleNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Resources.RoleNames", typeof(RoleNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni-Manager.
        /// </summary>
        internal static string AlumniManager {
            get {
                return ResourceManager.GetString("AlumniManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anticrisis Manager.
        /// </summary>
        internal static string AnticrisisManager {
            get {
                return ResourceManager.GetString("AnticrisisManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor.
        /// </summary>
        internal static string Auditor {
            get {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk.
        /// </summary>
        internal static string Clerk {
            get {
                return ResourceManager.GetString("Clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evangelist.
        /// </summary>
        internal static string Evangelist {
            get {
                return ResourceManager.GetString("Evangelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Director.
        /// </summary>
        internal static string GeneralDirector {
            get {
                return ResourceManager.GetString("GeneralDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacker.
        /// </summary>
        internal static string Hacker {
            get {
                return ResourceManager.GetString("Hacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR-Manager.
        /// </summary>
        internal static string HRManager {
            get {
                return ResourceManager.GetString("HRManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intern.
        /// </summary>
        internal static string Intern {
            get {
                return ResourceManager.GetString("Intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layoff Candidate.
        /// </summary>
        internal static string LayoffCandidate {
            get {
                return ResourceManager.GetString("LayoffCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master of Compromising.
        /// </summary>
        internal static string MasterOfCompromising {
            get {
                return ResourceManager.GetString("MasterOfCompromising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsourcer.
        /// </summary>
        internal static string Outsourcer {
            get {
                return ResourceManager.GetString("Outsourcer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Political Strategist.
        /// </summary>
        internal static string PoliticalStrategist {
            get {
                return ResourceManager.GetString("PoliticalStrategist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raider.
        /// </summary>
        internal static string Raider {
            get {
                return ResourceManager.GetString("Raider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Master.
        /// </summary>
        internal static string ScrumMaster {
            get {
                return ResourceManager.GetString("ScrumMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Specialist.
        /// </summary>
        internal static string SecuritySpecialist {
            get {
                return ResourceManager.GetString("SecuritySpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Director.
        /// </summary>
        internal static string ShadowDirector {
            get {
                return ResourceManager.GetString("ShadowDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shareholder.
        /// </summary>
        internal static string Shareholder {
            get {
                return ResourceManager.GetString("Shareholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy.
        /// </summary>
        internal static string Spy {
            get {
                return ResourceManager.GetString("Spy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Founder.
        /// </summary>
        internal static string StartupFounder {
            get {
                return ResourceManager.GetString("StartupFounder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administrator.
        /// </summary>
        internal static string SystemAdministrator {
            get {
                return ResourceManager.GetString("SystemAdministrator", resourceCulture);
            }
        }
    }
}
