//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VisitorDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisitorDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordBot.Resources.VisitorDescriptions", typeof(VisitorDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management issued a memorandum on staff optimization. We&apos;re likely down one employee..
        /// </summary>
        internal static string AllAnticrisisFire {
            get {
                return ResourceManager.GetString("AllAnticrisisFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like someone&apos;s going to be called in to speak to the principal soon....
        /// </summary>
        internal static string AllBlackmailMasterFire {
            get {
                return ResourceManager.GetString("AllBlackmailMasterFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are rumors going around the office about an upcoming restructuring..
        /// </summary>
        internal static string AllRaiderFire {
            get {
                return ResourceManager.GetString("AllRaiderFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A painfully familiar name appeared on the list of external contractors....
        /// </summary>
        internal static string AllResurrect {
            get {
                return ResourceManager.GetString("AllResurrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This morning, everyone saw a farewell message in the company chat. One of the colleagues had lost their temper and quit overnight..
        /// </summary>
        internal static string AllSuicide {
            get {
                return ResourceManager.GetString("AllSuicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jira experienced a massive outage. Someone fired themselves due to the incredible confusion in tickets!.
        /// </summary>
        internal static string AllSwapIncident {
            get {
                return ResourceManager.GetString("AllSwapIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fake letter from management has been sent. Let&apos;s see how they carry out someone else&apos;s orders....
        /// </summary>
        internal static string ExecutorControl {
            get {
                return ResourceManager.GetString("ExecutorControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You prepared irrefutable incriminating evidence against the target, but the lawyers rejected it because of the &quot;golden parachute&quot; in the target&apos;s contract..
        /// </summary>
        internal static string ExecutorFireImmune {
            get {
                return ResourceManager.GetString("ExecutorFireImmune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the closed staffing table, this person is {0}.
        /// </summary>
        internal static string ExecutorInvestigateRole {
            get {
                return ResourceManager.GetString("ExecutorInvestigateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cleaned up the employee&apos;s personnel file and destroyed all of his questionable activity before anyone saw it and forwarded it to the Director..
        /// </summary>
        internal static string ExecutorProtect {
            get {
                return ResourceManager.GetString("ExecutorProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logs don&apos;t lie. This employee is either working for competitors or pursuing personal agendas..
        /// </summary>
        internal static string ExecutorSecurityDetectDangerous {
            get {
                return ResourceManager.GetString("ExecutorSecurityDetectDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification has been passed. The employee is loyal to the Corporation..
        /// </summary>
        internal static string ExecutorSecurityDetectPeaceful {
            get {
                return ResourceManager.GetString("ExecutorSecurityDetectPeaceful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The candidate proved too principled and refused &quot;dirty&quot; money. He might become a problem..
        /// </summary>
        internal static string ExecutorShadowDirectorFail {
            get {
                return ResourceManager.GetString("ExecutorShadowDirectorFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Syndicate&apos;s offer has been accepted. We have a new agent within the Corporation..
        /// </summary>
        internal static string ExecutorShadowDirectorSuccess {
            get {
                return ResourceManager.GetString("ExecutorShadowDirectorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The candidate turned out to be too attached to a stable salary and bonuses..
        /// </summary>
        internal static string ExecutorStartupFounderFail {
            get {
                return ResourceManager.GetString("ExecutorStartupFounderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully sold the &quot;unicorn&quot; idea. Another cog in the system has become a freelance creator..
        /// </summary>
        internal static string ExecutorStartupFounderSuccess {
            get {
                return ResourceManager.GetString("ExecutorStartupFounderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You open your email and see: &quot;You don&apos;t fit into the company&apos;s new paradigm.&quot; You&apos;ve been hit with emergency budget cuts..
        /// </summary>
        internal static string TargetAnticrisisManagerFire {
            get {
                return ResourceManager.GetString("TargetAnticrisisManagerFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the morning you discover that someone has hacked your email and leaked your personal correspondence to management... You will be called to the director&apos;s office..
        /// </summary>
        internal static string TargetBlackmailMasterFire {
            get {
                return ResourceManager.GetString("TargetBlackmailMasterFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was blocked due to &quot;suspicious activity.&quot; You spent all night waiting for support, without doing anything..
        /// </summary>
        internal static string TargetBlock {
            get {
                return ResourceManager.GetString("TargetBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried to access a remote server, but one of the system administrators had already taken control and reset all your passwords!.
        /// </summary>
        internal static string TargetBlockBlocker {
            get {
                return ResourceManager.GetString("TargetBlockBlocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to a stupid mistake, you accidentally banned your own access token and were left without admin rights for the entire night..
        /// </summary>
        internal static string TargetBlockSelf {
            get {
                return ResourceManager.GetString("TargetBlockSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received an urgent and extremely strange order from your superiors via messenger. You couldn&apos;t disobey, so you had to put everything you had planned aside and carry it out..
        /// </summary>
        internal static string TargetControl {
            get {
                return ResourceManager.GetString("TargetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your competitors were undermining you overnight, but someone in HR deleted the incriminating logs. Your reputation is clear..
        /// </summary>
        internal static string TargetProtect {
            get {
                return ResourceManager.GetString("TargetProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the morning, you discover that your KPI in the system is significantly lower than it should be. You&apos;re sure it&apos;s the competitors&apos; doing. Get ready, you&apos;ll soon be laid off..
        /// </summary>
        internal static string TargetRaiderFire {
            get {
                return ResourceManager.GetString("TargetRaiderFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corporation showed you the door, but you immediately signed a shady B2B contract. You&apos;re back in business, but this time off-the-books. Now you are Outsourcer..
        /// </summary>
        internal static string TargetResurrect {
            get {
                return ResourceManager.GetString("TargetResurrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very strange and highly illegal collaboration proposal arrived in your work email, which you immediately marked as spam..
        /// </summary>
        internal static string TargetShadowDirectorFail {
            get {
                return ResourceManager.GetString("TargetShadowDirectorFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been made an offer you can&apos;t refuse. Large sums of money in exchange for a small favor. You&apos;re now a member of the Syndicate..
        /// </summary>
        internal static string TargetShadowDirectorSuccess {
            get {
                return ResourceManager.GetString("TargetShadowDirectorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were offered a job for an &quot;idea&quot; and illusory stock options, but you preferred stability..
        /// </summary>
        internal static string TargetStartupFounderFail {
            get {
                return ResourceManager.GetString("TargetStartupFounderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You signed an offer at a startup for a stake in the company and smoothies on Fridays. Corporate ideals are forgotten..
        /// </summary>
        internal static string TargetStartupFounderSuccess {
            get {
                return ResourceManager.GetString("TargetStartupFounderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You yourself don’t understand how, but for some reason you signed a letter of resignation of your own free will and gave it to the HR department. Now you are Evangelist..
        /// </summary>
        internal static string TargetSuicide {
            get {
                return ResourceManager.GetString("TargetSuicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suddenly, your priority tasks in the task tracker have been reassigned to a completely different project..
        /// </summary>
        internal static string TargetSwap {
            get {
                return ResourceManager.GetString("TargetSwap", resourceCulture);
            }
        }
    }
}
